#include <jni.h>        // JNI header provided by JDK
#include <stdio.h>      // C Standard IO Header
#include "HelloJNI.h"   // Generated by cmd
#include <iostream>
#include <string.h>

using namespace std;
// Implementation of the native method sayHello()
JNIEXPORT void JNICALL Java_HelloJNI_sayHello(JNIEnv *env, jobject thisObj,int num) {
   cout<<"Recieved From java : "<<num<<endl;
   return;
}
